### PR TITLE
coerce ccw to true or false to avoid inversions

### LINKED ISSUE #21: path.arc(…anticlockwise) must be true or 1, not truthy
We [have](https://github.com/d3/d3-path/blob/master/src/path.js#L90) `cw = 1 ^ ccw`

- 0, ~~"0"~~(edited), undefined, false => draws a clockwise arc
- 1, "1", true => draws an anticlockwise arc

So far so good, but trying with anticlockwise = "anticlockwise" or anticlockwise = 3 (or most other truthy values) will give a very weird path with an inverted curvature, because it will have both ccw truthy, and cw = 1.

I don't think the code should be fixed as this is probably the fastest approach, but maybe the documentation?

Currently we say
> If anticlockwise is true, the arc is drawn in the anticlockwise direction; otherwise, it is drawn in the clockwise direction

"otherwise" could be changed to "if false or undefined", or "if false"…

Another possibility:
> If anticlockwise, a boolean, is true, the arc is drawn in the anticlockwise direction; otherwise, it is drawn in the clockwise direction.

(I got bitten by using a checkbox’s value, which gave me anticlockwise="On".)

See interactive test at https://observablehq.com/d/d8c04cb491a6c444

### PR DESCRIPTION
**Pull request by Fil**
(fixes #21)

### CODE REVIEW

**Comment by mbostock** [comment]
I think `!!ccw` is more standard than `!!+ccw`. Any reason not to use the former?

**Comment by Fil** [comment]
It was for the case of "0".
- `!!` makes "0" true-ish
- `!!+` makes "0" false-ish

"0" is currently triggering the bug, which means we're sure that no-one uses it, and either solution is fine. Removing the + will save one byte :)

**Comment by mbostock** [comment]
But `"0"` is a truthy value, and thus should be interpreted as true rather than false.

```
if ("0") {
  console.log("it’s true");
}
```

**Comment by mbostock** [comment]
Rebased and merged to master.

**Pull request closed without merging**
